name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: vuepress-deploy
      uses: jickylive/vue-source@master
      env:
        ACCESS_TOKEN: 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
        TARGET_REPO: jickylive/vue
        TARGET_BRANCH: gh-pages
        BUILD_SCRIPT: yarn && yarn build
        BUILD_DIR: docs/.vuepress/public/
        COMMIT_MESSAGE:  Auto deploy by the Vuepress-deploy
